version: '2'
services:
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
  users:
    build: ../race-users/.
    ports:
      - 8081:3000
    depends_on:
      - mongodb
  race-config:
    build: ../race-config/.
    ports:
      - 8081:3000
    depends_on:
      - mongodb
      - users
